version: "3"

services:
  db-redis:
    image: redis
    ports:
      - "6379:6379"
  backend-java:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=db-redis
      - REDIS_PORT=6379
      - REDIS_CACHE_MINUTES=60
    command: sh -c "java -jar /backend/target/count-0.0.1-SNAPSHOT.jar"
    depends_on:
      - db-redis
    ports:
      - "8080:8080"